# Generated by Django 5.2.5 on 2025-08-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start', models.JSONField()),
                ('destinations', models.JSONField()),
                ('user_stations', models.JSONField(blank=True, null=True)),
                ('return_to_start', models.BooleanField(default=False)),
                ('initial_fuel', models.FloatField()),
                ('tank_capacity', models.FloatField()),
                ('consumption_km_per_unit', models.FloatField()),
                ('order_indices', models.JSONField(blank=True, null=True)),
                ('itinerary', models.JSONField(blank=True, null=True)),
                ('path', models.JSONField(blank=True, null=True)),
                ('total_distance_km', models.FloatField(blank=True, null=True)),
                ('total_duration_s', models.FloatField(blank=True, null=True)),
                ('fuel_units_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
